@startuml maquinaEstados

hide empty description

[*] -r-> PendienteDePreparacion : Registrar pedido \n / new()
PendienteDePreparacion -r-> EnPreparacion : Actualizar pedido \n / actualizar()
EnPreparacion -r-> PendienteDeFacturacion : Actualizar pedido \n / actualizar()
PendienteDePreparacion -d-> Cancelado : Registrar cancelacion \n / cancelar()
EnPreparacion -d-> Cancelado : Registrar cancelacion \n / cancelar()
PendienteDeFacturacion -d-> Cancelado : Registrar cancelacion \n / cancelar()
Cancelado --> [*]
PendienteDeFacturacion -d-> Facturado : Registrar cobro de pedido \n / registrarCobro()
Facturado --> [*]

@enduml